src/Entity/Formation.php
<?php

namespace App\Entity;

use App\Repository\FormationRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=FormationRepository::class)
 */
class Formation
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $titre;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $duree;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $date_debut;

    /**
     * @ORM\ManyToOne(targetEntity=Ecole::class, inversedBy="eformation")
     */
    private $ecole;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitre(): ?string
    {
        return $this->titre;
    }

    public function setTitre(string $titre): self
    {
        $this->titre = $titre;

        return $this;
    }

    public function getDuree(): ?string
    {
        return $this->duree;
    }

    public function setDuree(string $duree): self
    {
        $this->duree = $duree;

        return $this;
    }

    public function getDateDebut(): ?string
    {
        return $this->date_debut;
    }

    public function setDateDebut(string $date_debut): self
    {
        $this->date_debut = $date_debut;

        return $this;
    }

    public function getEcole(): ?Ecole
    {
        return $this->ecole;
    }

    public function setEcole(?Ecole $ecole): self
    {
        $this->ecole = $ecole;

        return $this;
    }
}

src/Form/FormationType.php
<?php

namespace App\Form;

use App\Entity\Formation;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class FormationType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('titre')
            ->add('duree')
            ->add('date_debut')
            ->add('ecole')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Formation::class,
        ]);
    }
}

src/Controller/FormationController.php
<?php

namespace App\Controller;

use App\Entity\Formation;
use App\Form\FormationType;
use App\Repository\FormationRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/formation")
 */
class FormationController extends AbstractController
{
    /**
     * @Route("/", name="app_formation_index", methods={"GET"})
     */
    public function index(FormationRepository $formationRepository): Response
    {
        return $this->render('formation/index.html.twig', [
            'formations' => $formationRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="app_formation_new", methods={"GET", "POST"})
     */
    public function new(Request $request, FormationRepository $formationRepository): Response
    {
        $formation = new Formation();
        $form = $this->createForm(FormationType::class, $formation);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $formationRepository->add($formation, true);

            return $this->redirectToRoute('app_formation_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('formation/new.html.twig', [
            'formation' => $formation,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="app_formation_show", methods={"GET"})
     */
    public function show(Formation $formation): Response
    {
        return $this->render('formation/show.html.twig', [
            'formation' => $formation,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="app_formation_edit", methods={"GET", "POST"})
     */
    public function edit(Request $request, Formation $formation, FormationRepository $formationRepository): Response
    {
        $form = $this->createForm(FormationType::class, $formation);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $formationRepository->add($formation, true);

            return $this->redirectToRoute('app_formation_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('formation/edit.html.twig', [
            'formation' => $formation,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="app_formation_delete", methods={"POST"})
     */
    public function delete(Request $request, Formation $formation, FormationRepository $formationRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$formation->getId(), $request->request->get('_token'))) {
            $formationRepository->remove($formation, true);
        }

        return $this->redirectToRoute('app_formation_index', [], Response::HTTP_SEE_OTHER);
    }

    /**
     * @Route("/relations", name="app_relations")
     */
    public function relations(FormationRepository $formationRepository): Response
    {
        $formations = $formationRepository->findAllWithEcole();

        return $this->render('relation.html.twig', [
            'formations' => $formations,
        ]);
    }
}

templates/formation/_delete_form.html.twig
<form method="post" action="{{ path('app_formation_delete', {'id': formation.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ formation.id) }}"><br />
    <button class="btn btn-danger btn-sm">Delete</button>
</form>

templates/formation/_form.html.twig
{{ form_start(form) }}
<center>
    {{ form_widget(form, {'attr': {'class': 'form-control'}}) }}<br /><br /><br /><br /><br />
    <button class="btn btn-primary">{{ button_label|default('Save') }}</button>
    <button href="{{ path('app_formation_index') }}" class="btn btn-secondary">back to list</button>
 </center>
{{ form_end(form) }}

templates/formation/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Formation{% endblock %}

{% block body %}
    <h1 style="text-align:center">Edit Formation</h1><br />

    {{ include('formation/_form.html.twig', {'button_label': 'Update'}) }}


{% endblock %}

templates/formation/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Formation index{% endblock %}

{% block body %}
<nav class="navbar navbar-expand-lg navbar-light" style="background-color: #e3f2fd;">
    <a class="navbar-brand" href="#"><b>Education</b></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link " href="{{ path('app_ecole_index') }}">Ecoles</a>
            </li>
            <li class="nav-item">
                <a class="nav-link active" href="{{ path('app_formation_index') }}">Formations</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{ path('app_relations') }}">Relations</a>
            </li>
        </ul>
    </div>
</nav>
<br />
    <h1 style="text-align:center; color: #007FFF; font-family: Helvetica">Formation </h1>
    <br />

    <table class="table table-bordered table-striped">
        <thead>
            <tr>
                <th scope="row">#</th>
                <th>Titre de formation</th>
                <th>Durée</th>
                <th>Date de debut</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for formation in formations %}
            <tr>
                <th scope="row">{{ formation.id }}</th>
                <td>{{ formation.titre }}</td>
                <td>{{ formation.duree }}</td>
                <td>{{ formation.dateDebut }}</td>
                <td>
                    <a href="{{ path('app_formation_show', {'id': formation.id}) }} " class="btn btn-info btn-sm">show</a>
                    <a href="{{ path('app_formation_edit', {'id': formation.id}) }}" class="btn btn-warning btn-sm">edit</a>
                    {{ include('formation/_delete_form.html.twig') }}
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="5">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

   <center> <a href="{{ path('app_formation_new') }}" class="btn btn-success">Create new</a></center>
{% endblock %}

templates/formation/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Formation{% endblock %}

{% block body %}
    <h1 style="text-align:center">Create new Formation</h1><br />

    {{ include('formation/_form.html.twig') }}

{% endblock %}

templates/formation/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Formation{% endblock %}

{% block body %}
    <div class="container mt-4">
    <h1 class="mb-4" style="text-align:center">Show Formation</h1>

    <table class="table table-bordered table-striped">
        <tbody>
            <tr>
                <th scope="row">Id</th>
                <td>{{ formation.id }}</td>
            </tr>
            <tr>
                <th scope="row">Titre</th>
                <td>{{ formation.titre }}</td>
            </tr>
            <tr>
                <th scope="row">Duree</th>
                <td>{{ formation.duree }}</td>
            </tr>
            <tr>
                <th scope="row">Date_debut</th>
                <td>{{ formation.dateDebut }}</td>
            </tr>
        </tbody>
    </table>
<center>
<a class="btn btn-warning" href="{{ path('app_formation_edit', {'id': formation.id}) }}">edit</a>
    <a class="btn btn-secondary" href="{{ path('app_formation_index') }}">back to list</a>
<br></br>
    </center>
    </div>
{% endblock %}